services:
  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    volumes:
      - ./nodejs:/usr/src/app
    restart: always
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nodejs
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-data:/var/lib/letsencrypt
    env_file:
      - .env

volumes:
  letsencrypt:
  letsencrypt-data:
  nodejs: